version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 0
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Build step"
          command: dotnet publish -c Release -r win10-x64
